/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#00685d",
        "primary-container": "#008376",
        "primary-fixed": "#8df5e4",
        "primary-fixed-dim": "#70d8c8",
        "on-primary": "#ffffff",
        "on-primary-container": "#f4fffb",
        "on-primary-fixed": "#00201c",
        "on-primary-fixed-variant": "#005048",
        "secondary": "#006398",
        "secondary-container": "#5bb8fe",
        "secondary-fixed": "#cce5ff",
        "secondary-fixed-dim": "#93ccff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00476e",
        "on-secondary-fixed": "#001d31",
        "on-secondary-fixed-variant": "#004b73",
        "tertiary": "#006b2c",
        "tertiary-container": "#00873a",
        "tertiary-fixed": "#7ffc97",
        "tertiary-fixed-dim": "#62df7d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f7fff2",
        "on-tertiary-fixed": "#002109",
        "on-tertiary-fixed-variant": "#005320",
        "surface": "#ebfdfa",
        "surface-dim": "#cbdedb",
        "surface-bright": "#ebfdfa",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#e5f7f5",
        "surface-container": "#dff2ef",
        "surface-container-high": "#daece9",
        "surface-container-highest": "#d4e6e4",
        "surface-variant": "#d4e6e4",
        "on-surface": "#0e1e1d",
        "on-surface-variant": "#3d4946",
        "outline": "#6d7a77",
        "outline-variant": "#bcc9c5",
        "background": "#ebfdfa",
        "on-background": "#0e1e1d",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#233332",
        "inverse-on-surface": "#e2f5f2",
        "inverse-primary": "#70d8c8"
      },
      fontFamily: {
        'display': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

